### ISSUE TITLE
The images generated by data_augment.py can't use for training

### ISSUE THREAD

**Issue by Susia00** [LeeRel1991/faceAlignment_tensorflow#2]
你好，有个疑问again：），用data_augment处理后的图片来训练，如处理afw并设置大小为112(256、512等)，都会报错“ssize.empty() in function 'resize'”，而用原训练集来训练就没问题，不知道这个报错该如何解决。另外，data_augment处理后的图片很多都是倒立的图片（虽可以设置角度），这种倒立的关键点图片是否有需要拿来训练呢?
具体报错如下：
2018-12-27 19:20:31.413676: W tensorflow/core/framework/op_kernel.cc:1306] Unknown: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):

File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in call
ret = func(*args)

File "../utils/data_loader.py", line 130, in load_sample_lable
img, kpt = self.preprocess(img, kpt)

File "../utils/data_cropper.py", line 105, in call
face_img = cv2.resize(face_img, self.out_size)

cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):
File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
return fn(*args)
File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):

File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in call
ret = func(*args)

File "../utils/data_loader.py", line 130, in load_sample_lable
img, kpt = self.preprocess(img, kpt)

File "../utils/data_cropper.py", line 105, in call
face_img = cv2.resize(face_img, self.out_size)

cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, arg1)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by LeeRel1991** [comment]
猜测问题可能两种情况。1.传给preprocess函数的kpt值不对，使得由此得到的bbox的宽高异常，人脸图片为空所以resize保存。2.data crop类有bug，导致从kpt 中crop的人脸数据异常。
建议训练前执行行visualize.py脚本先观察下图片和对应的groundtruth 是否正常，通过设置transform为none可观察增广后的原始数据， 通过设置transform为cropper来观察crop 预处理之后的数据。如果可视化的groundtruth原始数据正常而crop后报错，则很有可能是datacrop的bug，否则可能你的增广数据有问题。
注：工程中提供的增广脚本data_augment.py我这边是正常可用的（参考[官方版本ImageServer](https://github.com/MarekKowalski/DeepAlignmentNetwork/blob/master/DeepAlignmentNetwork/ImageServer.py)），但不排除其他bug。您也可以调用用官方TrainingSetPreparation.py ImageServer.py进行增广，然后调用我工程的ArrayDataset 代替PtsDataset 进行加载数据集给tf即可

**Comment by LeeRel1991** [comment]
抱歉，是工程里的data_augment.py问题，尽快修复。

**Comment by LeeRel1991** [comment]
data_augment 的bug已修复，原因在于DataAugment实例化时mirror和frame_fraction参数发生了错位。详细修改如下：
```python   
 augmenter = DataAugment(mean_shape,
                            augment_params["num"],
                            augment_params["perturbations"],
                            augment_params["out_size"],
                            mirror=augment_params["mirror"])
```

**Comment by LeeRel1991** [comment]
问题已解决

**Comment by octaviawfx** [comment]
> 你好，有个疑问again：），用data_augment处理后的图片来训练，如处理afw并设置大小为112(256、512等)，都会报错“ssize.empty() in function 'resize'”，而用原训练集来训练就没问题，不知道这个报错该如何解决。另外，data_augment处理后的图片很多都是倒立的图片（虽可以设置角度），这种倒立的关键点图片是否有需要拿来训练呢?
> 具体报错如下：
> 2018-12-27 19:20:31.413676: W tensorflow/core/framework/op_kernel.cc:1306] Unknown: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
> 
> Traceback (most recent call last):
> 
> File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in call
> ret = func(*args)
> 
> File "../utils/data_loader.py", line 130, in load_sample_lable
> img, kpt = self.preprocess(img, kpt)
> 
> File "../utils/data_cropper.py", line 105, in call
> face_img = cv2.resize(face_img, self.out_size)
> 
> cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
> 
> Traceback (most recent call last):
> File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
> return fn(*args)
> File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.UnknownError: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
> 
> Traceback (most recent call last):
> 
> File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in call
> ret = func(*args)
> 
> File "../utils/data_loader.py", line 130, in load_sample_lable
> img, kpt = self.preprocess(img, kpt)
> 
> File "../utils/data_cropper.py", line 105, in call
> face_img = cv2.resize(face_img, self.out_size)
> 
> cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
> 
> [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, arg1)]]
> [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[, ], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

请问 你的数据增强最后成功了吗？
