### ISSUE TITLE
where can I get meanImg.npy & stdImg.npy?

### ISSUE THREAD

**Issue by octaviawfx** [LeeRel1991/faceAlignment_tensorflow#3]
Appreciate a lot !!!!Very useful!!
But, where can I get meanImg.npy & stdImg.npy?

**Comment by LeeRel1991** [comment]
sorry, the global var _mean_img and _std_img is not used, so you can just comment or remove the two lines. Specifically, they are calculated on the trainset for normalizing the input images (i.e., (img-mean)/std). And there have been replaced by the mean and std of current image in the newest commit.
