### ISSUE TITLE
Make demo_fan.py?

### ISSUE THREAD

**Issue by sniper-for-14** [LeeRel1991/faceAlignment_tensorflow#4]
非常感谢代码！！！
我现在想利用 train_fan.py 训练人脸关键点检测， 但是我该如何从最后一层的输出[-1, 64, 64, 68]向量中得到每一个点的坐标值呢？
再次感谢！

**Comment by LeeRel1991** [comment]
fan网络模型的最后一层是64x64x68的关键点热度图分布，每个关键点对应一张64x64大小的热度图（heatmap）。[utils/data_utils.py](https://github.com/LeeRel1991/faceAlignment_tensorflow/blob/master/face_alignment/utils/data_utils.py)中的get_preds_from_hm 函数可将其转换成68X2的关键点坐标。用法参考[tools/eval_fan.py](https://github.com/LeeRel1991/faceAlignment_tensorflow/blob/master/face_alignment/tools/eval_fan.py) Line58-59。值得注意的是，由于fan网络的输入是256x256的图像，而输出是64x64,因此须将得到的关键点坐标恢值复到与输入尺寸一致（所以脚本中做了`x4`）
