### ISSUE TITLE
About initlandmarks.npy

### ISSUE THREAD

**Issue by octaviawfx** [LeeRel1991/faceAlignment_tensorflow#5]
index in initlandmarks.npy is the average value of all landmarks in pts file under "afw", 'helen/trainset', and "lfpw/trainset, can I say that?

**Comment by LeeRel1991** [comment]
Yes。And it is calculated on the trainset before augment.

**Comment by octaviawfx** [comment]
> Yes。And it is calculated on the trainset before augment.
Thank you for answering!!!
HI，I sew values in initLandmrk.py are between 20 and 90, so I guess I have to crop all images and then resize them to (112,112), is that right? If so, may I ask what scale did you used to get your initLandmark.py? In a word, I am trying to repeat your initLandmark.py.
Thanks for your time!!!

**Comment by LeeRel1991** [comment]
Yes， the  coordinates of pts in initLandmrk.npy  is corresponding to (112, 112). And there are two ways to generate it. 
The official version published by the author is that: 
first calculated the mean shape on the trainset, then for each sample image, get the best fit shape according to the meanshape (simply, transform mean shape into the current image according the labelled kpt, see the function best_fit_rect in [data_augment.py](https://github.com/LeeRel1991/faceAlignment_tensorflow/blob/master/face_alignment/tools/data_augment.py)), and finally select the first fitted one  in the training samples. See the author's implementation [ImageServer.py](https://github.com/MarekKowalski/DeepAlignmentNetwork/blob/master/DeepAlignmentNetwork/ImageServer.py)
There is another way by [zjjMaiMai](https://github.com/zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment), He just calculated the average groundtruth landmark of all the training images, see [processing.py](https://github.com/zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment/blob/master/DAN_V2/preprocessing.py). 

I will release the implementation code for it later.

**Comment by octaviawfx** [comment]
> Yes， the coordinates of pts in initLandmrk.npy is corresponding to (112, 112). And there are two ways to generate it.
> The official version published by the author is that:
> first calculated the mean shape on the trainset, then for each sample image, get the best fit shape according to the meanshape (simply, transform mean shape into the current image according the labelled kpt, see the function best_fit_rect in [data_augment.py](https://github.com/LeeRel1991/faceAlignment_tensorflow/blob/master/face_alignment/tools/data_augment.py)), and finally select the first fitted one in the training samples. See the author's implementation [ImageServer.py](https://github.com/MarekKowalski/DeepAlignmentNetwork/blob/master/DeepAlignmentNetwork/ImageServer.py)
> There is another way by [zjjMaiMai](https://github.com/zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment), He just calculated the average groundtruth landmark of all the training images, see [processing.py](https://github.com/zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment/blob/master/DAN_V2/preprocessing.py).
> 
> I will release the implementation code for it later.

That would be great, I'll be waiting!!!
Thanks a lot!
