### ISSUE TITLE
Was heatmap used in this DAN project?

### ISSUE THREAD

**Issue by octaviawfx** [LeeRel1991/faceAlignment_tensorflow#6]
I just realized that heatmap was only used  in FAN.
So,DAN was not used  in your project, is that right?

Thanks a lot!!!

**Comment by LeeRel1991** [comment]
Yes, the mechanism of heatmap is proposed by Hourglass network for body landmark location, and the FAN's paper applies the idea in facial landmark location task. Furthermore, DAN is a simple cascade regression with cnn to extract features.
