### ISSUE TITLE
dan_vgg_112_300WAugment error

### ISSUE THREAD

**Issue by tfapple** [LeeRel1991/faceAlignment_tensorflow#7]
您好，我在run demo_dan.py時出現以下訊息然後報錯:
NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model/dan_vgg_112_300WAugment
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
想請問此問題是因何而起呢?謝謝!!

**Comment by LeeRel1991** [comment]
可能是预训练的模型结构与待训练的网络结构不完全一致，导致网络中的某些参数在预训练权值文件中找不到。
你可以详细描述下您的需求和操作步骤，看看是不是哪里不合适
