### ISSUE TITLE
Are there any pretrained models?or some speed and model size infomation?

### ISSUE THREAD

**Issue by MaxwellHan** [LeeRel1991/faceAlignment_tensorflow#8]
是否可以提供预训练模型,或者有没有模型的大小和速度测试信息?

**Comment by LeeRel1991** [comment]
抱歉回复不及时，关于我这边训练和测试的预训练模型及性能参见readme，不完整还待更新，暂时提供一个[dan_vgg112的预训练模型](https://github.com/LeeRel1991/faceAlignment_tensorflow/releases)
