### ISSUE TITLE
请问data-augument.py中的meanFaceShape.npz是如何得到的？

### ISSUE THREAD

**Issue by terryzhangthu** [LeeRel1991/faceAlignment_tensorflow#9]
项目里面没有说名这个文件如何得到，谢谢

**Comment by LeeRel1991** [comment]
您好，该文件来自于DAN的作者实现里: https://github.com/MarekKowalski/DeepAlignmentNetwork/tree/master/data，
猜测是整个训练集的平均人脸形状(在112x112尺寸上居中)，已在最新提交([05c76d8](https://github.com/LeeRel1991/faceAlignment_tensorflow/commit/05c76d870d72526dbadfe90221cc275b72f2bce3))里添加了该文件

**Comment by terryzhangthu** [comment]
十分感谢回复，请问是这样做么？
1）原始训练图像中截取脸框？ 是紧贴着关键点的位置截取么，还是外扩一定的比例？
2）截取到的脸框resize到112x112
3）取平均，居中

**Comment by LeeRel1991** [comment]
对的，关于步骤1,有两种方案，有标注人脸检测框的，按人脸框截取，没有的按标注的人脸关键点的坐标范围，计算人脸框，有一定的向外扩边
